name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.8
      uses: actions/setup-node@v1
      with:
        node-version: 12.8
    - name: Install dependencies
      run: npm install
      working-directory: ./TATS
    - name: Install ionic
      run: npm i ionic
      working-directory: ./TATS
    - name: Lint
      run: npm run lint
      working-directory: ./TATS
    - name: Build
      run: npm run build -- --prod
      working-directory: ./TATS
    - name: Test
      run: npm test -- --configuration=ci
      working-directory: ./TATS
    - name: E2E
      run: npm run e2e -- --configuration=ci
      working-directory: ./TATS
